version: "3.9"
services:
  postgres:
    image: timescale/timescaledb:2.15.1-pg15
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
  redis:
    image: redis:7-alpine
  collector:
    build: ./app
    command: python collector.py
    env_file: .env
    depends_on: [redis]
  worker:
    build: ./app
    command: celery -A tasks worker --concurrency 2 --prefetch-multiplier 1
    env_file: .env
    depends_on: [redis, postgres]
  api:
    build: ./app
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    ports: [ "8000:8000" ]
    depends_on: [postgres]
  frontend:
    build: ./frontend
    command: npm run dev
    ports: [ "5174:5173" ]
volumes:
  db_data:
